### PR TITLE
Swap cypress for playwright for e2e tests

### PR DESCRIPTION
**Pull request by grantnorwood**
* Removed Cypress
* Installed [Playwright](https://playwright.dev/) and wrote a first homepage test
* Updated Development GitHub Action to run Playwright on pull requests and when merged to `main` in CI/CD

_(Keep in mind I'm a total Playwright noob, so feedback is a 🎁 !)_

### CODE REVIEW

**Comment by brookslybrand** [comment]
Looking good! I will do a more in-depth review once you get pipelines fixed. Let me know if you would like me to take a look at anything

**Comment by grantnorwood** [comment]
@brookslybrand  Ok, got the pipeline working.  Lemme know whatcha think.

**Comment by grantnorwood** [comment]
FYI, this last Cypress Tests pipeline failure is because I've updated the PR to point to the `development.yml@main` branch, which will run properly after merging to `main`.

Which is what I'm about to do!

Let's capture any feedback as a new PR.  I want to make sure the ci/cd actually works 🙂

**Comment by brookslybrand** [comment]
Hey @grantnorwood, so sorry I didn't get around to reviewing this before you merged it in. Going to take a look at everything and will put up a PR if I have any suggested changes

**Comment by grantnorwood** [comment]
No worries!  I just wanted to make sure ci/cd was working properly after merging, and I'll take a look at your cleanup PR.  Thanks!

**Pull request merged**
