### PR TITLE
Homepage optimizations

### PR DESCRIPTION
**Pull request by sethdavis512**
Small changes:

- Add `container` class to cards for better responsiveness
- Pull down and host jpgs
- Crop images to be the same ratio

### CODE REVIEW

**Comment by sethdavis512** [comment]
Ran lighthouse (desktop, before changes) and it wasn't terrible:

image

My changes target this issue:

image

**Review by KarenDouglas — APPROVED** [review]
This looks good to  me :)

**Comment by grantnorwood** [comment]
@sethdavis512 I didn't get a chance to leave this comment before you merged, but we could probably reduce the size/quality of the `hero.jpg` file.  As a background image with color overlay and content floating above, it probably doesn't need to be full jpg quality at 451k.

I created https://github.com/remix-austin/remixaustin-com/pull/38 with a compressed jpg which is about 1/3 of the size 🙂

**Comment by sethdavis512** [comment]
Yes! Nicely done

**Pull request merged**
