### PR TITLE
updating external links to open in new tab

### PR DESCRIPTION
**Pull request by KarenDouglas**

### CODE REVIEW

**Comment by KarenDouglas** [comment]
fixes #41

**Review by brookslybrand — APPROVED** [review]
Looks good to me! The component is getting pretty prop-y, so may want to refactor at some point, but I'm not too worried about it right now. Thanks for tackling this one!

**Comment by brookslybrand** [comment]
Feel free to merge whenever you'd like :

**Review by grantnorwood — APPROVED** [review]
Looks good!  Thanks @KarenDouglas!

**Pull request merged**
