### PR TITLE
Add support for blog tags with meta v2

### PR DESCRIPTION
**Pull request by matt-hernandez**
Better late than never 😆 

Adding support for blog tags by enabling meta v2

### CODE REVIEW

**Comment by brookslybrand** [comment]
Looks good to me @matt-hernandez! And better late than never 😅 

I did want to check the staging environment first, but then I remembered we have that issue with the ip allocation 🙃 

Looks like I've got it working if you're interested to approve first: https://github.com/remix-austin/remixaustin-com/pull/123

**Comment by brookslybrand** [comment]
Now that #123 is merged in, feel free to rebase off of/merge `main` into this MR, then add the `staging` flag back so we can test a deployed url 😎

**Comment by matt-hernandez** [comment]
@brookslybrand Staging deployed

**Review by brookslybrand — APPROVED** [review]
Whoops! So sorry @matt-hernandez, I forgot to hit the approve button 🤦

**Pull request merged**
