### PR TITLE
Add blog dependencies

### PR DESCRIPTION
**Pull request by matt-hernandez**
Here's the list of dependencies added and the purpose they serve:

Dependencies:

- `mdx-bundler` - This is the package that does the bulk of the work. It takes `.mdx` files, their dependencies, and creates front matter and a React component source string that can go in the DOM. This package is used on demand when users request a specific blog post.
- `remark-mdx-images` - This plugin works in tandem with `mdx-bundler` to take image dependencies and put them into the resulting React component source string as base64 encoded URLs. This allows images to be used in blog posts and show up instantly.
- `front-matter` - This package can take any markdown-like file and parse out its front matter. While `mdx-bundler` can do this functionality as well, `mdx-bundler` has to compile everything in order to get it. There's no way for it to just parse out the front matter. For making the top blog level page, where we list out only the top level details of every blog, we don't want to have to compile every single post to get this info. So we use `front-matter` instead.
- `fix-esm` - This one I'm not super proud of. `remark-mdx-images` is an ES Module instead of a CommonJS module. I could not for the live of me get it to play nice with our app. Our `tsconfig.json` is set up for CommonJS and I just couldn't get it to compile the import of `remark-mdx-images` without compile errors. So I used this npm package. It can make ES Modules compatible in our app. Because `remark-mdx-images` is used at runtime, this package is also a regular dependency. If someone can help with this, I'd appreciate it. Here's a code snippet of how it's used:
```typescript
const remarkMdxImages = require("fix-esm").require("remark-mdx-images");
```

Dev Dependencies:

- `ws` - This package makes it easy to run a web socket. It's what allows us to have auto-refresh functionality when modifying blog contents in dev mode.
- `@types/ws` - Types for the above package.
- `chokidar` - This is used to watch the blog files for changes and trigger the websocket to fire the message that causes the app to refresh in dev mode. `chokidar` has a few advantages over using `fs.watch`, mainly being that `fs.watch` can be super chatty when files change and send multiple events for the same change. This package helps us keep behavior predictable.
- `rimraf` - This package allows anyone using NodeJS to delete a folder and all of its files and subdirectories. It's the NodeJS version of the `rmdir -rf` command. This package is used in the build step of our project. It cleans out the directory for `/build/posts` so that the build can recreate that directory with updated content

### CODE REVIEW

**Comment by brookslybrand** [comment]
> fix-esm - This one I'm not super proud of

I was trying to see if [serverDependenciesToBundle](https://remix.run/docs/en/1.15.0/file-conventions/remix-config#serverdependenciestobundle) would solve things, but I think since `dev:posts` runs outside of Remix that's not going to work

I'm fine with going forward with this, but maybe let's make a ticket to follow up on it/see if anyone else can help. Wouldn't want this to stop us.

I'm also happy to write up that ticket, since you've already done so much 😄

**Comment by matt-hernandez** [comment]
Yeah, let's definitely get it written up somewhere so we can come back to it. Thanks

**Comment by brookslybrand** [comment]
See #94

**Review by brookslybrand — APPROVED** [review]
Great writeup, @matt-hernandez! Thanks so much for splitting these out. I'll go ahead and merge this in 🙂

**Pull request merged**
