### PR TITLE
Add initial blog foundation

### PR DESCRIPTION
**Pull request by sethdavis512**
Yo dawg, I heard you like blogs 😆 

Obviously the whole feature is not even close to being finished - wanted to get things off the ground. Added an MR for visibility. If you're reading this, please feel free to contribute to this branch 👍🏻

### CODE REVIEW

**Comment by brookslybrand** [comment]
@sethdavis512 you're the best! Definitely want to dig into this and give some ideas, hopefully early next week 😬

**Comment by colbywhite** [comment]
@sethdavis512 , curious your thoughts on #89

**Comment by matt-hernandez** [comment]
@colbywhite I like the idea of taking a wild stab at this by going with the filesystem route first, if only because it's the quickest and easiest way to get some kind of content hosted. I'd argue that everyone writing for the blog would theoretically have knowledge of markdown and how to use `.mdx` files. So even if it is a wild stab, I don't think it's crazy to have an integrated blog with this website using the codebase itself to store the blog content.

**Comment by matt-hernandez** [comment]
@colbywhite @sethdavis512 See #91 for my attempt

**Pull request closed without merging**
